//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShsKiosk.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tokenws.ucws.nhso.go.th/", ConfigurationName="ServiceReference1.UCWSTokenP1")]
    public interface UCWSTokenP1 {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tokenws.ucws.nhso.go.th/UCWSTokenP1/searchCurrentByPIDRequest", ReplyAction="http://tokenws.ucws.nhso.go.th/UCWSTokenP1/searchCurrentByPIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ShsKiosk.ServiceReference1.searchCurrentByPIDResponse searchCurrentByPID(ShsKiosk.ServiceReference1.searchCurrentByPIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tokenws.ucws.nhso.go.th/UCWSTokenP1/searchCurrentByPIDRequest", ReplyAction="http://tokenws.ucws.nhso.go.th/UCWSTokenP1/searchCurrentByPIDResponse")]
        System.Threading.Tasks.Task<ShsKiosk.ServiceReference1.searchCurrentByPIDResponse> searchCurrentByPIDAsync(ShsKiosk.ServiceReference1.searchCurrentByPIDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tokenws.ucws.nhso.go.th/")]
    public partial class nhsoDataSetC1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string birthdateField;
        
        private string cardidField;
        
        private string chatField;
        
        private int count_selectField;
        
        private string expdateField;
        
        private string fnameField;
        
        private string hmainField;
        
        private string hmain_nameField;
        
        private string hmain_opField;
        
        private string hmain_op_nameField;
        
        private string hsubField;
        
        private string hsub_nameField;
        
        private string lnameField;
        
        private string maininsclField;
        
        private string maininscl_mainField;
        
        private string maininscl_nameField;
        
        private string mastercup_idField;
        
        private string nationField;
        
        private System.DateTime new_date_registerField;
        
        private bool new_date_registerFieldSpecified;
        
        private string new_expdateField;
        
        private string new_hmainField;
        
        private string new_hmain_nameField;
        
        private string new_hmain_opField;
        
        private string new_hmain_op_nameField;
        
        private string new_hsubField;
        
        private string new_hsub_nameField;
        
        private string new_maininsclField;
        
        private string new_maininscl_nameField;
        
        private string new_mastercup_idField;
        
        private string new_paid_modelField;
        
        private string new_purchaseprovinceField;
        
        private string new_purchaseprovince_nameField;
        
        private string new_staffnameField;
        
        private string new_startdateField;
        
        private string new_subinsclField;
        
        private string new_subinscl_nameField;
        
        private string new_type_registerField;
        
        private string new_type_register_descField;
        
        private string paid_modelField;
        
        private string person_idField;
        
        private string primary_amphur_nameField;
        
        private string primary_mooField;
        
        private string primary_mooban_nameField;
        
        private string primary_province_nameField;
        
        private string primary_tumbon_nameField;
        
        private string primaryprovinceField;
        
        private string purchaseprovinceField;
        
        private string purchaseprovince_nameField;
        
        private string sexField;
        
        private string startdateField;
        
        private string startdate_sssField;
        
        private string statusField;
        
        private string status_descField;
        
        private string subinsclField;
        
        private string subinscl_nameField;
        
        private string titleField;
        
        private string title_nameField;
        
        private string ws_data_sourceField;
        
        private System.DateTime ws_date_requestField;
        
        private bool ws_date_requestFieldSpecified;
        
        private string ws_statusField;
        
        private string ws_status_descField;
        
        private string wsidField;
        
        private string wsid_batchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string birthdate {
            get {
                return this.birthdateField;
            }
            set {
                this.birthdateField = value;
                this.RaisePropertyChanged("birthdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cardid {
            get {
                return this.cardidField;
            }
            set {
                this.cardidField = value;
                this.RaisePropertyChanged("cardid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string chat {
            get {
                return this.chatField;
            }
            set {
                this.chatField = value;
                this.RaisePropertyChanged("chat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int count_select {
            get {
                return this.count_selectField;
            }
            set {
                this.count_selectField = value;
                this.RaisePropertyChanged("count_select");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string expdate {
            get {
                return this.expdateField;
            }
            set {
                this.expdateField = value;
                this.RaisePropertyChanged("expdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fname {
            get {
                return this.fnameField;
            }
            set {
                this.fnameField = value;
                this.RaisePropertyChanged("fname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string hmain {
            get {
                return this.hmainField;
            }
            set {
                this.hmainField = value;
                this.RaisePropertyChanged("hmain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string hmain_name {
            get {
                return this.hmain_nameField;
            }
            set {
                this.hmain_nameField = value;
                this.RaisePropertyChanged("hmain_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string hmain_op {
            get {
                return this.hmain_opField;
            }
            set {
                this.hmain_opField = value;
                this.RaisePropertyChanged("hmain_op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string hmain_op_name {
            get {
                return this.hmain_op_nameField;
            }
            set {
                this.hmain_op_nameField = value;
                this.RaisePropertyChanged("hmain_op_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string hsub {
            get {
                return this.hsubField;
            }
            set {
                this.hsubField = value;
                this.RaisePropertyChanged("hsub");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string hsub_name {
            get {
                return this.hsub_nameField;
            }
            set {
                this.hsub_nameField = value;
                this.RaisePropertyChanged("hsub_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string lname {
            get {
                return this.lnameField;
            }
            set {
                this.lnameField = value;
                this.RaisePropertyChanged("lname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string maininscl {
            get {
                return this.maininsclField;
            }
            set {
                this.maininsclField = value;
                this.RaisePropertyChanged("maininscl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string maininscl_main {
            get {
                return this.maininscl_mainField;
            }
            set {
                this.maininscl_mainField = value;
                this.RaisePropertyChanged("maininscl_main");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string maininscl_name {
            get {
                return this.maininscl_nameField;
            }
            set {
                this.maininscl_nameField = value;
                this.RaisePropertyChanged("maininscl_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string mastercup_id {
            get {
                return this.mastercup_idField;
            }
            set {
                this.mastercup_idField = value;
                this.RaisePropertyChanged("mastercup_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string nation {
            get {
                return this.nationField;
            }
            set {
                this.nationField = value;
                this.RaisePropertyChanged("nation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public System.DateTime new_date_register {
            get {
                return this.new_date_registerField;
            }
            set {
                this.new_date_registerField = value;
                this.RaisePropertyChanged("new_date_register");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool new_date_registerSpecified {
            get {
                return this.new_date_registerFieldSpecified;
            }
            set {
                this.new_date_registerFieldSpecified = value;
                this.RaisePropertyChanged("new_date_registerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string new_expdate {
            get {
                return this.new_expdateField;
            }
            set {
                this.new_expdateField = value;
                this.RaisePropertyChanged("new_expdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string new_hmain {
            get {
                return this.new_hmainField;
            }
            set {
                this.new_hmainField = value;
                this.RaisePropertyChanged("new_hmain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string new_hmain_name {
            get {
                return this.new_hmain_nameField;
            }
            set {
                this.new_hmain_nameField = value;
                this.RaisePropertyChanged("new_hmain_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string new_hmain_op {
            get {
                return this.new_hmain_opField;
            }
            set {
                this.new_hmain_opField = value;
                this.RaisePropertyChanged("new_hmain_op");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string new_hmain_op_name {
            get {
                return this.new_hmain_op_nameField;
            }
            set {
                this.new_hmain_op_nameField = value;
                this.RaisePropertyChanged("new_hmain_op_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string new_hsub {
            get {
                return this.new_hsubField;
            }
            set {
                this.new_hsubField = value;
                this.RaisePropertyChanged("new_hsub");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string new_hsub_name {
            get {
                return this.new_hsub_nameField;
            }
            set {
                this.new_hsub_nameField = value;
                this.RaisePropertyChanged("new_hsub_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string new_maininscl {
            get {
                return this.new_maininsclField;
            }
            set {
                this.new_maininsclField = value;
                this.RaisePropertyChanged("new_maininscl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string new_maininscl_name {
            get {
                return this.new_maininscl_nameField;
            }
            set {
                this.new_maininscl_nameField = value;
                this.RaisePropertyChanged("new_maininscl_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string new_mastercup_id {
            get {
                return this.new_mastercup_idField;
            }
            set {
                this.new_mastercup_idField = value;
                this.RaisePropertyChanged("new_mastercup_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string new_paid_model {
            get {
                return this.new_paid_modelField;
            }
            set {
                this.new_paid_modelField = value;
                this.RaisePropertyChanged("new_paid_model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string new_purchaseprovince {
            get {
                return this.new_purchaseprovinceField;
            }
            set {
                this.new_purchaseprovinceField = value;
                this.RaisePropertyChanged("new_purchaseprovince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string new_purchaseprovince_name {
            get {
                return this.new_purchaseprovince_nameField;
            }
            set {
                this.new_purchaseprovince_nameField = value;
                this.RaisePropertyChanged("new_purchaseprovince_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string new_staffname {
            get {
                return this.new_staffnameField;
            }
            set {
                this.new_staffnameField = value;
                this.RaisePropertyChanged("new_staffname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string new_startdate {
            get {
                return this.new_startdateField;
            }
            set {
                this.new_startdateField = value;
                this.RaisePropertyChanged("new_startdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string new_subinscl {
            get {
                return this.new_subinsclField;
            }
            set {
                this.new_subinsclField = value;
                this.RaisePropertyChanged("new_subinscl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string new_subinscl_name {
            get {
                return this.new_subinscl_nameField;
            }
            set {
                this.new_subinscl_nameField = value;
                this.RaisePropertyChanged("new_subinscl_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string new_type_register {
            get {
                return this.new_type_registerField;
            }
            set {
                this.new_type_registerField = value;
                this.RaisePropertyChanged("new_type_register");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string new_type_register_desc {
            get {
                return this.new_type_register_descField;
            }
            set {
                this.new_type_register_descField = value;
                this.RaisePropertyChanged("new_type_register_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string paid_model {
            get {
                return this.paid_modelField;
            }
            set {
                this.paid_modelField = value;
                this.RaisePropertyChanged("paid_model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string person_id {
            get {
                return this.person_idField;
            }
            set {
                this.person_idField = value;
                this.RaisePropertyChanged("person_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string primary_amphur_name {
            get {
                return this.primary_amphur_nameField;
            }
            set {
                this.primary_amphur_nameField = value;
                this.RaisePropertyChanged("primary_amphur_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string primary_moo {
            get {
                return this.primary_mooField;
            }
            set {
                this.primary_mooField = value;
                this.RaisePropertyChanged("primary_moo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string primary_mooban_name {
            get {
                return this.primary_mooban_nameField;
            }
            set {
                this.primary_mooban_nameField = value;
                this.RaisePropertyChanged("primary_mooban_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string primary_province_name {
            get {
                return this.primary_province_nameField;
            }
            set {
                this.primary_province_nameField = value;
                this.RaisePropertyChanged("primary_province_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string primary_tumbon_name {
            get {
                return this.primary_tumbon_nameField;
            }
            set {
                this.primary_tumbon_nameField = value;
                this.RaisePropertyChanged("primary_tumbon_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string primaryprovince {
            get {
                return this.primaryprovinceField;
            }
            set {
                this.primaryprovinceField = value;
                this.RaisePropertyChanged("primaryprovince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string purchaseprovince {
            get {
                return this.purchaseprovinceField;
            }
            set {
                this.purchaseprovinceField = value;
                this.RaisePropertyChanged("purchaseprovince");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string purchaseprovince_name {
            get {
                return this.purchaseprovince_nameField;
            }
            set {
                this.purchaseprovince_nameField = value;
                this.RaisePropertyChanged("purchaseprovince_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string startdate {
            get {
                return this.startdateField;
            }
            set {
                this.startdateField = value;
                this.RaisePropertyChanged("startdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string startdate_sss {
            get {
                return this.startdate_sssField;
            }
            set {
                this.startdate_sssField = value;
                this.RaisePropertyChanged("startdate_sss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string status_desc {
            get {
                return this.status_descField;
            }
            set {
                this.status_descField = value;
                this.RaisePropertyChanged("status_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string subinscl {
            get {
                return this.subinsclField;
            }
            set {
                this.subinsclField = value;
                this.RaisePropertyChanged("subinscl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string subinscl_name {
            get {
                return this.subinscl_nameField;
            }
            set {
                this.subinscl_nameField = value;
                this.RaisePropertyChanged("subinscl_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string title_name {
            get {
                return this.title_nameField;
            }
            set {
                this.title_nameField = value;
                this.RaisePropertyChanged("title_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string ws_data_source {
            get {
                return this.ws_data_sourceField;
            }
            set {
                this.ws_data_sourceField = value;
                this.RaisePropertyChanged("ws_data_source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public System.DateTime ws_date_request {
            get {
                return this.ws_date_requestField;
            }
            set {
                this.ws_date_requestField = value;
                this.RaisePropertyChanged("ws_date_request");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ws_date_requestSpecified {
            get {
                return this.ws_date_requestFieldSpecified;
            }
            set {
                this.ws_date_requestFieldSpecified = value;
                this.RaisePropertyChanged("ws_date_requestSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string ws_status {
            get {
                return this.ws_statusField;
            }
            set {
                this.ws_statusField = value;
                this.RaisePropertyChanged("ws_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string ws_status_desc {
            get {
                return this.ws_status_descField;
            }
            set {
                this.ws_status_descField = value;
                this.RaisePropertyChanged("ws_status_desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string wsid {
            get {
                return this.wsidField;
            }
            set {
                this.wsidField = value;
                this.RaisePropertyChanged("wsid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string wsid_batch {
            get {
                return this.wsid_batchField;
            }
            set {
                this.wsid_batchField = value;
                this.RaisePropertyChanged("wsid_batch");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchCurrentByPID", WrapperNamespace="http://tokenws.ucws.nhso.go.th/", IsWrapped=true)]
    public partial class searchCurrentByPIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tokenws.ucws.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_person_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tokenws.ucws.nhso.go.th/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string smctoken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tokenws.ucws.nhso.go.th/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string person_id;
        
        public searchCurrentByPIDRequest() {
        }
        
        public searchCurrentByPIDRequest(string user_person_id, string smctoken, string person_id) {
            this.user_person_id = user_person_id;
            this.smctoken = smctoken;
            this.person_id = person_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchCurrentByPIDResponse", WrapperNamespace="http://tokenws.ucws.nhso.go.th/", IsWrapped=true)]
    public partial class searchCurrentByPIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tokenws.ucws.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShsKiosk.ServiceReference1.nhsoDataSetC1 @return;
        
        public searchCurrentByPIDResponse() {
        }
        
        public searchCurrentByPIDResponse(ShsKiosk.ServiceReference1.nhsoDataSetC1 @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UCWSTokenP1Channel : ShsKiosk.ServiceReference1.UCWSTokenP1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UCWSTokenP1Client : System.ServiceModel.ClientBase<ShsKiosk.ServiceReference1.UCWSTokenP1>, ShsKiosk.ServiceReference1.UCWSTokenP1 {
        
        public UCWSTokenP1Client() {
        }
        
        public UCWSTokenP1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UCWSTokenP1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UCWSTokenP1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UCWSTokenP1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShsKiosk.ServiceReference1.searchCurrentByPIDResponse ShsKiosk.ServiceReference1.UCWSTokenP1.searchCurrentByPID(ShsKiosk.ServiceReference1.searchCurrentByPIDRequest request) {
            return base.Channel.searchCurrentByPID(request);
        }
        
        public ShsKiosk.ServiceReference1.nhsoDataSetC1 searchCurrentByPID(string user_person_id, string smctoken, string person_id) {
            ShsKiosk.ServiceReference1.searchCurrentByPIDRequest inValue = new ShsKiosk.ServiceReference1.searchCurrentByPIDRequest();
            inValue.user_person_id = user_person_id;
            inValue.smctoken = smctoken;
            inValue.person_id = person_id;
            ShsKiosk.ServiceReference1.searchCurrentByPIDResponse retVal = ((ShsKiosk.ServiceReference1.UCWSTokenP1)(this)).searchCurrentByPID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShsKiosk.ServiceReference1.searchCurrentByPIDResponse> ShsKiosk.ServiceReference1.UCWSTokenP1.searchCurrentByPIDAsync(ShsKiosk.ServiceReference1.searchCurrentByPIDRequest request) {
            return base.Channel.searchCurrentByPIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShsKiosk.ServiceReference1.searchCurrentByPIDResponse> searchCurrentByPIDAsync(string user_person_id, string smctoken, string person_id) {
            ShsKiosk.ServiceReference1.searchCurrentByPIDRequest inValue = new ShsKiosk.ServiceReference1.searchCurrentByPIDRequest();
            inValue.user_person_id = user_person_id;
            inValue.smctoken = smctoken;
            inValue.person_id = person_id;
            return ((ShsKiosk.ServiceReference1.UCWSTokenP1)(this)).searchCurrentByPIDAsync(inValue);
        }
    }
}
